# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - v*

#pool:
#  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    ubuntu-p35:
      imageName: 'ubuntu-latest'
      python.version: '3.5'
    ubuntu-p36:
      imageName: 'ubuntu-latest'
      python.version: '3.6'
    ubuntu-p37:
      imageName: 'ubuntu-latest'
      python.version: '3.7'
    ubuntu-p38:
      imageName: 'ubuntu-latest'
      python.version: '3.8'
    macOS-p37:
      imageName: 'macOS-latest'
      python.version: '3.7'
    macOS-p38:
      imageName: 'macOS-latest'
      python.version: '3.8'
    windows-p35:
      imageName: 'windows-latest'
      python.version: '3.5'
    windows-p36:
      imageName: 'windows-latest'
      python.version: '3.6'
    windows-p37:
      imageName: 'windows-latest'
      python.version: '3.7'
    windows-p38:
      imageName: 'windows-latest'
      python.version: '3.8'


pool:
  vmImage: $(imageName)


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    brew install gfortran

    python -m pip install --upgrade pip setuptools

    pip install -r requirements_dev.txt

  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest

  displayName: 'pytest'
